[inputoutput]

path_to_input_channel1 = "Data/ATP/230302_ATPOS_Beladung_100x_488-4-2-frame-duplicated-image.tif"
path_to_input_channel2 = "Data/ATP/230302_ATPOS_Beladung_100x_561-4-2-frame-duplicated-image-duplicate.tif"
# path_to_input_channel1 = "Data/ATP/230221_ATPOS_Optimierung_1_w1Dual-CF-488-561-camera2-1-duplicate-10frames.tif"
# path_to_input_channel2 = "Data/ATP/230221_ATPOS_Optimierung_1_w2Dual-CF-561-488-camera1-1-duplicate-10frames.tif"
# path_to_input_combined = "Data/170424 JMP HN1L-KO Beads/170424 HN1L K2 OKT3 Beads/170424 2.tif"
path_to_input_combined = "Data/170424 JMP HN1L-KO Beads/170424 HN1L K2 OKT3 Beads/170424 2-1-short.tif"

path_to_output = ""

[properties]

# can either be "two-in-one" or "single"
# (where in the latter, the two input channels are in separate files)

channel_format = "two-in-one"
wavelength_1 = 488
wavelength_2 = 561
# further information regarding the imaging:
laserpower_wavelength_1 = 0.6 # e.g. 60%, important for bleaching correction
laserpower_wavelength_2 = 0.4 # 40%
scale_microns_per_pixel = 0 # Maßstab/scale: Wieviele Mikrometer pro Pixel?
estimated_cell_diameter_in_pixels = 100 # ATP: 100 for 100x and 60 for 63x, but not safe...
cell_type = "CD4 positive murine T-cells"

# TO DO Fura etc.
ATP = false
