[input_output]
file_or_directory = "dir"
image_conf = "two-in-one"
path = "/Users/testuser/Documents/GitHub/DARTS/Data/debug/test_file"
results_dir = "/Users/testuser/Documents/GitHub/DARTS/results/debug"
excel_filename_microdomain_data = "microdomain_data.xlsx"

[properties_of_measurement]
used_microscope = "left"
scale = 6.5359
frame_rate = 40.0
resolution = 3
cell_type = "test"
day_of_measurement = "2023-12-16"
user = "testuser"
experiment_name = "hotspot_startpoint_def_no_beads"
imaging_local_or_global = "local"
bead_contact = false
duration_of_measurement = 1280.0
wavelength_1 = 488
wavelength_2 = 561
time_of_measurement_before_starting_point = 2.0
time_of_measurement_after_starting_point = 30.0

[properties_of_measurement.calibration_parameters_cell_type]
a = 1.0
b = 1.0
c = 1.0
d = 1.0
aInv = 1.0
bInv = 1.0
cInv = 1.0
dInv = 1.0
spotHeight = 100.0

[processing_pipeline]
[processing_pipeline.postprocessing]
channel_alignment_in_pipeline = false
channel_alignment_each_frame = false
registration_method = "SITK"
background_sub_in_pipeline = false
cell_segmentation_tracking_in_pipeline = true
deconvolution_in_pipeline = false
deconvolution_algorithm = "LR"
TDE_lambda = ""
TDE_lambda_t = ""
bleaching_correction_in_pipeline = false
bleaching_correction_algorithm = "additiv no fit"
ratio_images = true
median_filter_kernel = 3

[processing_pipeline.postprocessing.psf]
type = "confocal"
lambdaEx_ch1 = 488
lambdaEm_ch1 = 520
lambdaEx_ch2 = 488
lambdaEm_ch2 = 600
numAper = 1.4
magObj = 100
rindexObj = 1.518
ccdSize = 6450
dz = 0
nslices = 1
depth = 0
rindexSp = 1.518
nor = 0
xysize = 150

[processing_pipeline.shape_normalization]
shape_normalization = false

[processing_pipeline.analysis]
hotspot_detection = true
dartboard_projection = false
