[input_output]
image_conf = "two-in-one"
path_to_input_1 = ""
path_to_input_2 = ""
path_to_input_combined = "/Users/dejan/Documents/GitHub/T-DARTS/Data/debug/test_file"
results_dir = "/Users/dejan/Documents/GitHub/T-DARTS/results/debug"
excel_filename_microdomain_data = "microdomain_data.xlsx"

[properties_of_measurement]
used_microscope = "left"
scale = 6.5359
frame_rate = 40.0
resolution = 3
cell_type = "jurkat"
day_of_measurement = "2023-11-27"
user = "dejan"
experiment_name = "test"
duration_of_measurement = 600
wavelength_1 = 488
wavelength_2 = 561

[processing_pipeline]
[processing_pipeline.postprocessing]
channel_alignment_in_pipeline = true
channel_alignment_each_frame = false
registration_method = "SITK"
background_sub_in_pipeline = true
cell_segmentation_tracking_in_pipeline = true
deconvolution_in_pipeline = true
deconvolution_algorithm = "LR"
TDE_lambda = ""
TDE_lambda_t = ""
bead_contact = true
bleaching_correction_in_pipeline = true
bleaching_correction_algorithm = "additiv no fit"
ratio_images = true
median_filter_kernel = 3

[processing_pipeline.postprocessing.psf]
type = "confocal"
lambdaEx_ch1 = 488
lambdaEm_ch1 = 520
lambdaEx_ch2 = 488
lambdaEm_ch2 = 600
numAper = 1.4
magObj = 100
rindexObj = 1.518
ccdSize = 6450
dz = 0
nslices = 1
depth = 0
rindexSp = 1.518
nor = 0
xysize = 150

[processing_pipeline.shape_normalization]
shape_normalization = true

[processing_pipeline.analysis]
hotspot_detection = true
dartboard_projection = true
#