[inputoutput]


path_to_input_channel1 = "Data/ATP/230302_ATPOS_Beladung_100x_488-4-2-frame-duplicated-image.tif"
path_to_input_channel2 = "Data/ATP/230302_ATPOS_Beladung_100x_561-4-2-frame-duplicated-image-duplicate.tif"

path_to_input_combined = "Data/170424 JMP HN1L-KO Beads/170424 HN1L K2 OKT3 Beads/170424 2.tif"


path_to_output = "results"
excel_filename = "output.xlsx"

start_frame = 0
end_frame = 30


[properties]

# can either be "two-in-one" or "single"
# (where in the latter, the two input channels are in separate files)

channel_format = "two-in-one"
wavelength_1 = 488
wavelength_2 = 561
# further information regarding the imaging:
laserpower_wavelength_1 = 0.6 # e.g. 60%, important for bleaching correction
laserpower_wavelength_2 = 0.4 # 40%
scale_microns_per_pixel = 3.0 # Maßstab/scale: Wieviele Mikrometer pro Pixel?
estimated_cell_diameter_in_pixels = 100 # ATP: 100 for 100x and 60 for 63x, but not safe...
cell_type = "jurkat"  # ['jurkat', 'primary', 'NK']
frames_per_second = 20.0 # how many frames are being measured per second?
spatial_resolution = 3 # pixels
ratio_preactivation_threshold = 1.0
dartboard_number_of_sections = 12
dartboard_number_of_areas_per_section = 8


# TO DO Fura etc.

registration_method = "SITK"
registration_framebyframe = false

ATP = false
