source 'https://rubygems.org'

# Force a modern version of the github-pages bundle that supports Ruby 3.x
gem "github-pages", "~> 231", group: :jekyll_plugins

# Specify jekyll cleanly (github-pages will automatically manage the exact jekyll version)
gem "just-the-docs", "~> 0.13"

# old
# gem "jekyll", "~> 4.3.2" # installed by `gem jekyll`
# gem "webrick"        # required when using Ruby >= 3 and Jekyll <= 4.2.2
# gem "just-the-docs", "0.4.0"


